config/routes.rb
READ_ACTIONS  = %i(:index :show)
WRITE_ACTIONS = %i(:new :edit :update :delete)

Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  constraints Clearance::Constraints::SignedIn.new do
    resources :user_players
    resources :district_factions
    resources :district_characters
    resources :faction_characters
    resources :player_traumas
    resources :players
    resources :characters
    resources :factions
    resources :categories
    resources :districts
    resources :games do
      member do
        get :join
      end
    end
    root "dashboard#index"
  end

  constraints Clearance::Constraints::SignedOut.new do
    resources :games, only: READ_ACTIONS do
      member do
        get :join
      end
      resources :categories
      resources :characters
      resources :districts
      resources :factions
      resources :players
    end
    root 'dashboard#landing', as: :signed_out_root
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def landing
    render layout: 'landing'
  end

  def index
    render locals: {
      my_games: current_user.games,
      playing_games: Array(current_user.game)
    }
  end
end

app/views/dashboard/index.html.slim
= link_to 'New Game', new_game_path, class: 'btn-primary'
h2 Games I'm Running
- my_games.each do |game|
  h4 
    = link_to game, game
  - if game.join_token
    p
      strong Join Link
      br
      = link_to game, join_game_path(game) + "?token=#{game.join_token}"
    p 
      strong Players
      ul
        li = game.user.email
        - game.users do |user|
          li = user.email
      


hr

h2 Games I'm Playing
- playing_games.each do |game|
  = elm(game)

app/views/dashboard/landing.html.slim
section.splash
  .login
    = link_to 'Sign in', sign_in_path, class: 'btn-primary'    
  h1 Risky Standard
  h5
    small Your notes now have a great effect
section.learn-more
  = link_to 'Learn More', '#features', class: 'btn-primary'
section#features.features
  h2 Features
  
  .feature-set
    .feature
      h4.title Organize Your Notes
      
    .feature
      h4.title Quickly Make Edits To Factions and Players
    
    .feature
      h4.title Share With Your Players To Build Together
      
    .feature.coming-soon
      h4.title Roll Your Dice Right here
      
    .feature.coming-soon
      h4.title Group Text Chat
      
    .feature.coming-soon
      h4.title File / Image Upload
footer.landing
  p = link_to "Sign Up", sign_up_path
  p = link_to "Sign In", sign_in_path
  p = link_to "Blades In The Dark", "http://www.evilhat.com/home/blades-in-the-dark/" 