config/routes.rb
READ_ACTIONS  = %i(:index :show)
WRITE_ACTIONS = %i(:new :edit :update :delete)

Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  constraints Clearance::Constraints::SignedIn.new do
    resources :user_players
    resources :district_factions
    resources :district_characters
    resources :faction_characters
    resources :player_traumas
    resources :players
    resources :characters
    resources :factions
    resources :categories
    resources :districts
    resources :games do
      member do
        get :join
      end
    end
    root "dashboard#index"
  end

  constraints Clearance::Constraints::SignedOut.new do
    resources :games, only: READ_ACTIONS do
      member do
        get :join
      end
      resources :categories
      resources :characters
      resources :districts
      resources :factions
      resources :players
    end
    root 'dashboard#landing', as: :signed_out_root
  end
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :game
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  def index
    @characters = Character.all
  end

  # GET /characters/1
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  def create
    @character = Character.new(character_params)

    if @character.save
      redirect_to @character, notice: 'Character was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /characters/1
  def update
    if @character.update(character_params)
      redirect_to @character, notice: 'Character was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /characters/1
  def destroy
    @character.destroy
    redirect_to characters_url, notice: 'Character was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def character_params
      params.require(:character).permit(:game_id, :name, :description)
    end
end

app/views/characters/_form.html.slim
= form_for @character do |f|
  - if @character.errors.any?
    #error_explanation
      h2 = "#{pluralize(@character.errors.count, "error")} prohibited this character from being saved:"
      ul
        - @character.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :game
    = f.text_field :game
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .actions = f.submit class: 'btn-primary'

app/views/characters/edit.html.slim
h1 Editing character

== render 'form'

= link_to 'Show', @character
'|
= link_to 'Back', characters_path

app/views/characters/index.html.slim
h1 Listing characters

table
  thead
    tr
      th Game
      th Name
      th Description
      th
      th
      th

  tbody
    - @characters.each do |character|
      tr
        td = character.game
        td = character.name
        td = character.description
        td = link_to 'Show', character
        td = link_to 'Edit', edit_character_path(character)
        td = link_to 'Destroy', character, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Character', new_character_path, class: 'btn-primary'

app/views/characters/new.html.slim
h1 New character

== render 'form'

= link_to 'Back', characters_path

app/views/characters/show.html.slim
p#notice = notice

p
  strong Game:
  = @character.game
p
  strong Name:
  = @character.name
p
  strong Description:
  = @character.description

= link_to 'Edit', edit_character_path(@character)
'|
= link_to 'Back', characters_path