config/routes.rb
READ_ACTIONS  = %i(:index :show)
WRITE_ACTIONS = %i(:new :edit :update :delete)

Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  constraints Clearance::Constraints::SignedIn.new do
    resources :user_players
    resources :district_factions
    resources :district_characters
    resources :faction_characters
    resources :player_traumas
    resources :players
    resources :characters
    resources :factions
    resources :categories
    resources :districts
    resources :games do
      member do
        get :join
      end
    end
    root "dashboard#index"
  end

  constraints Clearance::Constraints::SignedOut.new do
    resources :games, only: READ_ACTIONS do
      member do
        get :join
      end
      resources :categories
      resources :characters
      resources :districts
      resources :factions
      resources :players
    end
    root 'dashboard#landing', as: :signed_out_root
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  def index
    @players = Player.all
  end

  # GET /players/1
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to @player, notice: 'Player was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /players/1
  def update
    if @player.update(player_params)
      redirect_to @player, notice: 'Player was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /players/1
  def destroy
    @player.destroy
    redirect_to players_url, notice: 'Player was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def player_params
      params.require(:player).permit(:game_id, :name, :description, :playbook, :stress, :coin)
    end
end

app/views/players/_form.html.slim
= form_for @player do |f|
  - if @player.errors.any?
    #error_explanation
      h2 = "#{pluralize(@player.errors.count, "error")} prohibited this player from being saved:"
      ul
        - @player.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :game
    = f.text_field :game
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :playbook
    = f.text_field :playbook
  .field
    = f.label :stress
    = f.number_field :stress
  .field
    = f.label :coin
    = f.number_field :coin
  .actions = f.submit class: 'btn-primary'

app/views/players/edit.html.slim
h1 Editing player

== render 'form'

= link_to 'Show', @player
'|
= link_to 'Back', players_path

app/views/players/index.html.slim
h1 Listing players

table
  thead
    tr
      th Game
      th Name
      th Description
      th Playbook
      th Stress
      th Coin
      th
      th
      th

  tbody
    - @players.each do |player|
      tr
        td = player.game
        td = player.name
        td = player.description
        td = player.playbook
        td = player.stress
        td = player.coin
        td = link_to 'Show', player
        td = link_to 'Edit', edit_player_path(player)
        td = link_to 'Destroy', player, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Player', new_player_path, class: 'btn-primary'

app/views/players/new.html.slim
h1 New player

== render 'form'

= link_to 'Back', players_path

app/views/players/show.html.slim
p#notice = notice

p
  strong Game:
  = @player.game
p
  strong Name:
  = @player.name
p
  strong Description:
  = @player.description
p
  strong Playbook:
  = @player.playbook
p
  strong Stress:
  = @player.stress
p
  strong Coin:
  = @player.coin

= link_to 'Edit', edit_player_path(@player)
'|
= link_to 'Back', players_path