config/routes.rb
READ_ACTIONS  = %i(:index :show)
WRITE_ACTIONS = %i(:new :edit :update :delete)

Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  constraints Clearance::Constraints::SignedIn.new do
    resources :user_players
    resources :district_factions
    resources :district_characters
    resources :faction_characters
    resources :player_traumas
    resources :players
    resources :characters
    resources :factions
    resources :categories
    resources :districts
    resources :games do
      member do
        get :join
      end
    end
    root "dashboard#index"
  end

  constraints Clearance::Constraints::SignedOut.new do
    resources :games, only: READ_ACTIONS do
      member do
        get :join
      end
      resources :categories
      resources :characters
      resources :districts
      resources :factions
      resources :players
    end
    root 'dashboard#landing', as: :signed_out_root
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=edge"]
    meta[name="description" content=""]
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    title
      = local_assigns.fetch(:title, [controller_name, action_name].map(&:titleize).join(" - "))
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true

  body
    #left
    #right
    nav
      input type='checkbox' id='mobile-menu'
      label.mobile-menu for='mobile-menu'
      .list
        - if signed_in?
          .list-item
            - if current_user.multiple_games?
              = current_user.game
              = link_to "Change" "#"
            - else 
              = link_to current_user.game, root_path
          = link_to categories_path, class: 'list-item action'
            p Factions
          = link_to districts_path, class: 'list-item action'
            p Districts
          / li = link_to "Characters", characters_path
          / li = link_to "Players", players_path
          .list-item = button_to 'Sign out', sign_out_path, class: 'btn-primary', method: :delete
          / li = "Signed in as: #{current_user.email}"
        - else
          .list-item = link_to 'Sign in', sign_in_path, class: 'btn-primary'


    - flash.each do |key, value|
      .flash class = key
        = value

    .main-content
      .container
        = yield

    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_pack_tag 'application'
    script
      = yield :elm

app/views/layouts/landing.html.slim
doctype html
html
  head
    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=edge"]
    meta[name="description" content=""]
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    title
      = local_assigns.fetch(:title, [controller_name, action_name].map(&:titleize).join(" - "))
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true

  body
    #left
    #right
    = yield

    = javascript_include_tag 'application', 'data-turbolinks-track' => true